version: "3.9"

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node
    depends_on:
      - mongo
    ports:
      - 8080:8080
    networks:
      - server

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: todo
    networks:
      - server

networks:
  server:
    driver: bridge
